# Alacritty configuration

window:
  opacity: 0.95
  decorations: full

font:
  normal:
    family: "FiraCode Nerd Font"
    style: Regular
  size: 14

colors:
  primary:
    background: '0x1e1e2e'
    foreground: '0xcdd6f4'
  normal:
    black:   '0x45475a'
    red:     '0xf38ba8'
    green:   '0xa6e3a1'
    yellow:  '0xf9e2af'
    blue:    '0x89b4fa'
    magenta: '0xcba6f7'
    cyan:    '0x94e2d5'
    white:   '0xbac2de'
  bright:
    black:   '0x585b70'
    red:     '0xf38ba8'
    green:   '0xa6e3a1'
    yellow:  '0xf9e2af'
    blue:    '0x89b4fa'
    magenta: '0xcba6f7'
    cyan:    '0x94e2d5'
    white:   '0xa6adc8'

cursor:
  style: Beam
  blink_interval: 500

mouse:
  hide_when_typing: true

scrolling:
  history: 10000
